### PR TITLE
Remove time sync

### PR DESCRIPTION
**Pull request by corygehr**
Removes fields used for skew estimation, which is no longer required.

@rajanchari for awareness

### CODE REVIEW

**Comment by rajan-chari** [comment]
do we need as_of?

**Comment by corygehr** [comment]
@ataymano added something similar before we discussed the time sync issue... do you remember what it was for?

**Comment by corygehr** [comment]
@rajan-chari It was added to eliminate the client's need to calculate the maximum timestamp in the batch - makes it quicker for them to know the next 'lastTimestamp' value they need to provide in the future. It should be renamed to be more clear on this.

**Comment by rajan-chari** [comment]
The rename makes sense.  Also saw some comments in the proto around sync that might need updating.

**Comment by rajan-chari** [comment]
I don't see a way for me to change status to Approved.  Looks good to me.

**Pull request merged**
